import sys
sys.path.append('D:/Python/coding-exercises/Python3/utility')
from edabit_tester import EdabitTester
from shortest import findShortestWords

Test = EdabitTester()

Test.assert_equals(findShortestWords("Strive not to be a success, but rather to be of value."), ['a'])
Test.assert_equals(findShortestWords("You miss 100% of the shots you don't take."), ['of'])
Test.assert_equals(findShortestWords("Life is what happens to you while you're busy making other plans."), ['is', 'to'])
Test.assert_equals(findShortestWords("We become what we think about."), ['we', 'we'])
Test.assert_equals(findShortestWords("The most common way people give up their power is by thinking they don't have any."), ['by', 'is', 'up'])
Test.assert_equals(findShortestWords("The best time to plant the tree was 20 years ago. The second best time is now."), ['is', 'to'])
Test.assert_equals(findShortestWords("Your time is limited, so don't waste it living someone else's life."), ['is', 'it', 'so'])
Test.assert_equals(findShortestWords("You can never cross the ocean until you have the courage to lose sight of the shore."), ['of', 'to'])
Test.assert_equals(findShortestWords("There is only one way to avoid criticism: do nothing, say nothing, and be nothing."), ['be', 'do', 'is', 'to' ])
Test.assert_equals(findShortestWords("The only person you are destined to become is the person you decide to be."), ['be', 'is', 'to', 'to'])
Test.assert_equals(findShortestWords("What lies behind us and what lies before us are tiny matters compared to what lies within us."), ['to', 'us', 'us', 'us'])
Test.assert_equals(findShortestWords("If you are depressed you are living in the past. If you are anxious you are living in the future. If you are at peace you are living in the present."), ['at', 'if', 'if', 'if', 'in', 'in', 'in'])
Test.assert_equals(findShortestWords("Happiness depends upon ourselves."), ['upon'])
Test.assert_equals(findShortestWords("Chase two rabbits, catch none."), ['two'])
Test.assert_equals(findShortestWords("Only the truth of who you are, if realized, will set you free."), ['if', 'of'])
Test.assert_equals(findShortestWords("If you end up with a boring miserable life because you listened to your parents, your teacher, your priest, or some guy on television, then you deserve it."), ['a'])
Test.assert_equals(findShortestWords("To accomplish great things, we must not only act, but also dream; not only plan, but also believe."), ['to', 'we'])
Test.assert_equals(findShortestWords("A tiger doesn't lose sleep over the opinion of sheep."), ['a'])
Test.assert_equals(findShortestWords("Kindness is a language that the deaf can hear and the blind can see."), ['a'])
Test.assert_equals(findShortestWords("Being realistic is the most common path to mediocrity."), ['is', 'to'])
Test.assert_equals(findShortestWords("Bravery means finding something more important than fear."), ['fear', 'more', 'than'])
Test.assert_equals(findShortestWords("Can you imagine what I would do if I could do all I can?"), ['i', 'i', 'i'])
Test.assert_equals(findShortestWords("Believe you can and you're halfway there."), ['and', 'can', 'you'])
Test.assert_equals(findShortestWords("Remember that happiness is a way of travel, not a destination."), ['a', 'a'])
Test.assert_equals(findShortestWords("May the best day of your past be the worst day of your future."), ['be', 'of', 'of'])
Test.assert_equals(findShortestWords("a. b, c! d_ e/ f? g# hi j$ k% l^ m& n* o( p) q- r= s+ t| u[ v] w{ x} y@ z< A>"), ['a', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'])

Test.summary()
